name : egison-tutorial
cmdname : egison-tutorial
summary : A tutorial program for the Egison programming language
description : A tutorial program for the Egison programming language
version : 3.9.3
changelog : Support Egison 3.9.3
url : https://www.egison.org/
author : Satoshi, Egi
email : <egison@egison.org>
libdir : /usr/lib
