language: generic

services:
  - docker

matrix:
    include:
        - os: linux

before_install:
    - sudo apt update
    - sudo apt install jq

install:
    - true

script:
    - bash -x release.sh init
    - travis_wait 20 bash -x release.sh bump
    - travis_wait 40 bash -x release.sh upload-tarball
    - travis_wait 20 bash -x release.sh upload-rpm
