language: generic

# cabal install is failed on trusty
dist: xenial

matrix:
    include:
        - os: linux

before_install:
    - sudo apt update
    - sudo apt install jq cabal-install ghc

install:
    - true

script:
    - bash -x release.sh init
    - travis_wait 40 bash -x release.sh bump
