language: generic

services:
  - docker

matrix:
    include:
        - os: linux
          env: BUILDER=egison/egison-package-builder TARGET=egison/egison

before_install:
    - sudo apt update
    - sudo apt install -y jq
    - docker pull greymd/egison-deb-builder:latest
    - docker pull greymd/egison-rpm-builder:latest
    - docker pull greymd/egison-tarball-builder:latest

install:
    - true

script:
    - bash -x release.sh init
    - travis_wait 20 bash -x release.sh bump "$BUILDER" "$TARGET"
    - travis_wait 40 bash -x release.sh upload-tarball "$BUILDER" "$TARGET" "$BUILDER"
    - travis_wait 20 bash -x release.sh upload-rpm "$BUILDER" "$TARGET" "$BUILDER"
    - travis_wait 20 bash -x release.sh upload-deb "$BUILDER" "$TARGET" "$BUILDER"
    - travis_wait 20 bash -x release.sh commit-rpm "$BUILDER" "$TARGET" "$BUILDER"
    - travis_wait 20 bash -x release.sh commit-deb "$BUILDER" "$TARGET" "$BUILDER"
