language: generic

services:
  - docker

matrix:
    include:
        - os: linux

before_install:
    - docker pull greymd/rpm-egison
    - sudo apt update
    - sudo apt install jq

install:
    - true

script:
    - bash -x release.sh init
    - travis_wait 60 docker run greymd/rpm-egison > egison.tar.gz
    - file egison.tar.gz
    - tar tvf egison.tar.gz
    - travis_wait 60 bash -x release.sh bump
